"""
Django settings for lic_api project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from os import getenv
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. The URL to use when referring to static files
STATIC_URL = 'static/'

# 2. The absolute path to the directory where collectstatic will collect static files for deployment.
# On your server, this will be /home/ubuntu/lic_api/staticfiles
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 3. Extra places for collectstatic to find static files (like your frontend build)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv('SECRET_KEY')


# URL to access media via browser
MEDIA_URL = 'media/'

# Absolute path to the folder on the server
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = [
    '54.161.31.236',
    'diatomaceous-preventively-amber.ngrok-free.dev',
    'langataislamiccenter.org',
    'localhost',
    '127.0.0.1',
    'langata-islamic-center.vercel.app',
    'liwomasjid.co.ke',
    'langataislamiccenter.org',
    'www.langataislamiccenter.org',
    '[::1]',
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    # Local apps
    'users',
    'projects',
    'donations',
    'ratings',
    'contact',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lic_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lic_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# CORS Configuration
CSRF_TRUSTED_ORIGINS = [
    "https://langataislamiccenter.org",
    "https://www.langataislamiccenter.org",
    "https://liwomasjid.co.ke",
]
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://langata-islamic-center.vercel.app",
    "http://liwomasjid.co.ke",
    "https://liwomasjid.co.ke",
    "https://www.langataislamiccenter.org",
    "https://langataislamiccenter.org",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

#MPESA
MPESA_CONSUMER_KEY = getenv('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = getenv('MPESA_CONSUMER_SECRET')
MPESA_PASSKEY = getenv('MPESA_PASSKEY')
MPESA_SHORTCODE = getenv('MPESA_SHORTCODE')
MPESA_BASE_URL = getenv('MPESA_BASE_URL')
MPESA_CALLBACK_URL = getenv('MPESA_CALLBACK_URL')

# Stripe Configuration
# Attempt to get Live keys, fallback to Test keys, then fallback to None
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY') or os.getenv('TEST_STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY') or os.getenv('TEST_STRIPE_SECRET_KEY')

# PayPal Configuration
PAYPAL_CLIENT_ID = getenv('PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = getenv('PAYPAL_CLIENT_SECRET')
PAYPAL_MODE = getenv('PAYPAL_MODE', 'sandbox')

# Paystack Configuration
PAYSTACK_SECRET_KEY = getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = getenv('PAYSTACK_PUBLIC_KEY')

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = getenv('AWS_S3_REGION_NAME')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_DEFAULT_ACL = None

# Use S3 for static and media storage
# Tell Django to use S3 for Media files
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
